### ISSUE TITLE
Add code files per programming language

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Travis-CI#10]
dep https://github.com/tapaswenipathak/Travis-CI/issues/1.

- [ ] C
- [ ] C++
- [ ] Generic
- [ ] Java
- [ ] JS
- [ ] Perl
- [ ] PHP
- [ ] Python

**Comment by gurungrahul2** [comment]
All languages to be added:
  C
  C++
  Generic
  Java
  JS
  Perl
  PHP
  Python

**Comment by gurungrahul2** [comment]
Please tell your expectation, you want just programming files only or respective `.travis.yml` files too ?

**Comment by tapaswenipathak** [comment]
On Fri, May 17, 2019 at 11:03 PM R. Gurung <notifications@github.com> wrote:
>
> Please tell your expectation, you want just programming files only or respective .travis.yml files as well ?

`.travis.yml` are present in the repository, you should add code files
enabling parallel travis execution.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by kurianbenoy** [comment]
Can I work on this?
