### ISSUE TITLE
Add Travis CI badge

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Travis-CI#11]
dep #10.

**Comment by rahgurung** [comment]
@tapaswenipathak I don't understand this, where should we add the badge ? This repo doesn't even have an integrated Travis.

**Comment by tapaswenipathak** [comment]
On Mon, May 13, 2019 at 6:54 PM R. Gurung <notifications@github.com> wrote:
>
> @tapaswenipathak I don't understand this, where should we add the badge ? This repo doesn't even have an integrated Travis.

Travis can only be enabled after the repository have a code file per
programming language, so the dep. I then enable Travis and than the
badge can be added.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
