### ISSUE TITLE
Add a website

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Travis-CI#4]
I just need a HTML type website, hosted on Heroku.

- Sign up in an [Heroku](https://id.heroku.com/login) account.
- Deploy the website.
- Take credentials from me.
- Deploy on my Heroku account.

**Comment by Siddharth1698** [comment]
ill do it

**Comment by sakshivij** [comment]
Is this issue open to work on? I would like to work on it

**Comment by tapaswenipathak** [comment]
On Tue, May 14, 2019 at 8:40 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> Is this issue open to work on? I would like to work on it

Sure!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by sakshivij** [comment]
The website doesn't need to be on any specific topic?

**Comment by tapaswenipathak** [comment]
On Tue, May 14, 2019 at 11:38 PM SAKSHI VIJ <notifications@github.com> wrote:
>
> The website should be on any specific topic?

I cut a ticket https://github.com/tapaswenipathak/Internship/issues/43.
Extra thoughts, closing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
